gpt-4:
    import: "./openai-chat-azure-4.yaml"
    parameters:
        name: "gpt-4"
        body:
            max_tokens: 512
gpt-35-turbo:
    import: "./openai-chat-azure-35.yaml"
    parameters:
        name: "gpt-35-turbo"
        body:
            max_tokens: 512
