import: definition.yaml

concurrency:
  task:
    dbbench-std: 3
    os-std: 3
  agent:
    gpt-4: 3
    gpt-35-turbo: 3

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-35-turbo
      - gpt-4
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"
